# Generated by Django 6.1 on 2026-09-02 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(max_length=200)),
                ('evaluator_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('evaluator_organization', models.CharField(blank=True, max_length=200, null=True)),
                ('problem_innovation', models.IntegerField(default=3, help_text='Problem & Innovation (20%)')),
                ('technical_excellence', models.IntegerField(default=3, help_text='Technical Excellence (25%)')),
                ('functionality_demo', models.IntegerField(default=3, help_text='Functionality & Demonstration (20%)')),
                ('presentation_team', models.IntegerField(default=3, help_text='Presentation & Team Competence (15%)')),
                ('industry_impact', models.IntegerField(default=3, help_text='Industry Impact & Readiness (20%)')),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.project')),
            ],
            options={
                'verbose_name': 'Project Evaluation',
                'verbose_name_plural': 'Project Evaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
