# Generated by Django 6.1 on 2026-09-02 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectevaluation',
            name='evaluator_email',
        ),
        migrations.RemoveField(
            model_name='projectevaluation',
            name='evaluator_name',
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL),
        ),
    ]
